### ISSUE TITLE
acggov图片发送错误

### ISSUE THREAD

**Issue by dexzopiclone** [pcrbot/setu_renew#12]
[2021-02-07 20:25:43,807 setu] INFO: Message 2089367511 triggered send_search_setu by RexTrigger.
[2021-02-07 20:25:43,807 setu] ERROR: <class 'IndexError'> occured when send_search_setu handling message 2089367511.
[2021-02-07 20:25:43,807 setu] ERROR: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/user/Source/Repos/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/home/user/Source/Repos/HoshinoBot/hoshino/modules/setu_renew/__init__.py", line 236, in send_search_setu
    msg = await get_setu(gid)
  File "/home/user/Source/Repos/HoshinoBot/hoshino/modules/setu_renew/base.py", line 61, in get_setu
    image = await acggov_get_setu()
  File "/home/user/Source/Repos/HoshinoBot/hoshino/modules/setu_renew/acggov.py", line 373, in acggov_get_setu
    return get_setu_native()
  File "/home/user/Source/Repos/HoshinoBot/hoshino/modules/setu_renew/acggov.py", line 303, in get_setu_native
    fn = random.choice(os.listdir(res.path))
  File "/home/user/.conda/envs/hoshinobot/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

res/img/setu_mix/acggov/
目录下确实是空的……

**Comment by dexzopiclone** [comment]
https://github.com/pcrbot/setu_renew/blob/b73a457cc89c692d84fd94cb7f3566b8c4fad67a/base.py#L121
注释去掉就好了……

**Comment by dexzopiclone** [comment]
去掉注释就好了
https://github.com/pcrbot/setu_renew/blob/b73a457cc89c692d84fd94cb7f3566b8c4fad67a/base.py#L121
