### ISSUE TITLE
比较奇怪，看不出问题

### ISSUE THREAD

**Issue by JMFANS** [pcrbot/setu_renew#41]
Traceback (most recent call last):                                             File "/root/hoshino/hoshino/hoshino/modules/setu_renew/acggov.py", line 103, in query_setu
    data = await resp.json(content_type='application/json')
  File "/root/hoshino/hoshino_venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.acgmx.com/public/setu')

**Comment by corvo007** [comment]
api坏了或者改endpoint了
