### ISSUE TITLE
lolicon_r18无法正常工作

### ISSUE THREAD

**Issue by river0Love** [pcrbot/setu_renew#43]
[2021-10-08 10:58:06,058 涩图] INFO: Message 2645 triggered send_search_setu.
[2021-10-08 10:58:06,059 涩图] ERROR: <class 'IndexError'> occured when send_search_setu handling message 2645.
[2021-10-08 10:58:06,059 涩图] ERROR: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/root/yuanshenbot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/yuanshenbot/hoshino/modules/setu_renew/__init__.py", line 285, in send_search_setu
    msg = await get_setu(gid)
  File "/root/yuanshenbot/hoshino/modules/setu_renew/base.py", line 80, in get_setu
    image = await lolicon_get_setu(1)
  File "/root/yuanshenbot/hoshino/modules/setu_renew/lolicon.py", line 270, in lolicon_get_setu
    return get_setu_native(r18)
  File "/root/yuanshenbot/hoshino/modules/setu_renew/lolicon.py", line 213, in get_setu_native
    fn = random.choice(os.listdir(res.path))
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by corvo007** [comment]
https://github.com/pcrbot/setu_renew/blob/5ecb981ed2c5f4ee81001e975514145cb9603105/README.md#L24
