### ISSUE TITLE
没有办法发送色图

### ISSUE THREAD

**Issue by cmdhb** [pcrbot/setu_renew#49]
[2021-11-08 17:41:30,934 涩图] INFO: Message 1085609283 triggered send_search_setu.
[2021-11-08 17:41:30,934 涩图] ERROR: <class 'IndexError'> occured when send_search_setu handling message 1085609283.
[2021-11-08 17:41:30,934 涩图] ERROR: list index out of range
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/setu_renew/__init__.py", line 285, in send_search_setu
    msg = await get_setu(gid)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/setu_renew/base.py", line 78, in get_setu
    image = await lolicon_get_setu(0)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 271, in lolicon_get_setu
    return get_setu_native(r18)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/setu_renew/lolicon.py", line 214, in get_setu_native
    fn = random.choice(os.listdir(res.path))
  File "/usr/local/lib/python3.9/random.py", line 347, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by corvo007** [comment]
https://github.com/pcrbot/setu_renew#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by cmdhb** [comment]
缓存不了啊
