### ISSUE TITLE
AssertionError: Service name "涩图" already exist!

### ISSUE THREAD

**Issue by dfmjndm** [pcrbot/setu_renew#62]
查了一下也没发现modules里面有同名插件，同名函数都没有
把service名称修改照样会以新名称报重复错误
这可能是什么原因呢

[2022-07-16 18:30:06,700 nonebot] INFO: Succeeded to import and load "hoshino.modules.fake_message.fake_message"
[2022-07-16 18:30:06,714 nonebot] ERROR: Failed to import and load "hoshino.modules.setu_renew.acggov", error: Expecting value: line 1 column 1 (char 0)
[2022-07-16 18:30:06,717 nonebot] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/setu_renew/__init__.py", line 96, in <module>
    from .base import *
  File "/hobot/hoshino/modules/setu_renew/base.py", line 11, in <module>
    from .acggov import acggov_fetch_process, acggov_get_ranking, acggov_get_ranking_setu, acggov_get_setu, acggov_init, \
  File "/hobot/hoshino/modules/setu_renew/acggov.py", line 15, in <module>
    from .config import get_config
  File "/hobot/hoshino/modules/setu_renew/config.py", line 19, in <module>
    group_list = json.load(open(grouplistpath, 'r', encoding='utf8'))
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-07-16 18:30:06,723 nonebot] ERROR: Failed to import and load "hoshino.modules.setu_renew.lolicon", error: Service name "涩图" already exist!
[2022-07-16 18:30:06,723 nonebot] ERROR: Service name "涩图" already exist!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/setu_renew/__init__.py", line 16, in <module>
    sv = hoshino.Service('涩图', bundle='pcr娱乐', help_=HELP_MSG)
  File "/hobot/hoshino/service.py", line 124, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "涩图" already exist!
[2022-07-16 18:30:06,724 nonebot] ERROR: Failed to import and load "hoshino.modules.setu_renew.base", error: Service name "涩图" already exist!
[2022-07-16 18:30:06,724 nonebot] ERROR: Service name "涩图" already exist!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/setu_renew/__init__.py", line 16, in <module>
    sv = hoshino.Service('涩图', bundle='pcr娱乐', help_=HELP_MSG)
  File "/hobot/hoshino/service.py", line 124, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "涩图" already exist!
[2022-07-16 18:30:06,726 nonebot] ERROR: Failed to import and load "hoshino.modules.setu_renew.config", error: Service name "涩图" already exist!
[2022-07-16 18:30:06,726 nonebot] ERROR: Service name "涩图" already exist!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/setu_renew/__init__.py", line 16, in <module>
    sv = hoshino.Service('涩图', bundle='pcr娱乐', help_=HELP_MSG)
  File "/hobot/hoshino/service.py", line 124, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "涩图" already exist!

**Comment by dfmjndm** [comment]
而且lolicon.py里面填的是"setu_mix/~"这个路径也很奇怪，一定要装setu_mix吗
